### ISSUE TITLE
PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by 89z** [google/brotli#954]
Using Pip, I can install and uninstall packages fine:

~~~
PS D:\Desktop> pip install mutagen
Collecting mutagen
  Using cached mutagen-1.45.1-py3-none-any.whl (218 kB)
Installing collected packages: mutagen
Successfully installed mutagen-1.45.1
PS D:\Desktop> pip uninstall -y mutagen
Found existing installation: mutagen 1.45.1
Uninstalling mutagen-1.45.1:
  Successfully uninstalled mutagen-1.45.1
~~~

but not Brotli:

~~~
PS D:\Desktop> pip install brotli
Collecting brotli
  Using cached Brotli-1.0.9-cp310-cp310-win_amd64.whl (383 kB)
Installing collected packages: brotli
Successfully installed brotli-1.0.9
PS D:\Desktop> pip uninstall -y brotli
Found existing installation: Brotli 1.0.9
Uninstalling Brotli-1.0.9:
  Successfully uninstalled Brotli-1.0.9
ERROR: Exception:
Traceback (most recent call last):
  File "C:\python\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\python\lib\site-packages\pip\_internal\commands\uninstall.py", line 102, in run
    uninstall_pathset.commit()
  File "C:\python\lib\site-packages\pip\_internal\req\req_uninstall.py", line 420, in commit
    self._moved_paths.commit()
  File "C:\python\lib\site-packages\pip\_internal\req\req_uninstall.py", line 273, in commit
    save_dir.cleanup()
  File "C:\python\lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "C:\python\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "C:\python\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\python\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "C:\python\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "concurrent\futures\_base.py", line 439, in result
  File "concurrent\futures\_base.py", line 391, in __get_result
  File "C:\python\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "C:\python\lib\site-packages\pip\_internal\utils\misc.py", line 124, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "shutil.py", line 739, in rmtree
  File "shutil.py", line 617, in _rmtree_unsafe
  File "shutil.py", line 615, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\Windows\\Temp\\pip-uninstall-29ty1w8w\\_brotli.cp310-win_amd64.pyd'
~~~

**Comment by 89z** [comment]
Pip issue, not brotli
